// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 0002_keytoken.sql

package database

import (
	"context"
	"encoding/json"
)

const addUsedToken = `-- name: AddUsedToken :exec
UPDATE ` + "`" + `keytoken` + "`" + `
SET refresh_tokens_used = CASE
    WHEN refresh_tokens_used IS NULL THEN JSON_ARRAY(?)
    ELSE JSON_ARRAY_APPEND(refresh_tokens_used, '$', ?)
END,
update_at = CURRENT_TIMESTAMP
WHERE account_id = ?
`

type AddUsedTokenParams struct {
	JSONARRAY       interface{}
	JSONARRAYAPPEND interface{}
	AccountID       string
}

func (q *Queries) AddUsedToken(ctx context.Context, arg AddUsedTokenParams) error {
	_, err := q.db.ExecContext(ctx, addUsedToken, arg.JSONARRAY, arg.JSONARRAYAPPEND, arg.AccountID)
	return err
}

const deleteKey = `-- name: DeleteKey :exec
DELETE FROM ` + "`" + `keytoken` + "`" + ` WHERE account_id = ?
`

func (q *Queries) DeleteKey(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteKey, accountID)
	return err
}

const getKeyByAccountID = `-- name: GetKeyByAccountID :one

SELECT id, account_id, refresh_token, refresh_tokens_used 
FROM ` + "`" + `keytoken` + "`" + ` 
WHERE account_id = ?
`

type GetKeyByAccountIDRow struct {
	ID                string
	AccountID         string
	RefreshToken      string
	RefreshTokensUsed json.RawMessage
}

// Nếu NULL, đặt giá trị mặc định là JSON_ARRAY()
func (q *Queries) GetKeyByAccountID(ctx context.Context, accountID string) (GetKeyByAccountIDRow, error) {
	row := q.db.QueryRowContext(ctx, getKeyByAccountID, accountID)
	var i GetKeyByAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshToken,
		&i.RefreshTokensUsed,
	)
	return i, err
}

const insertKey = `-- name: InsertKey :exec
INSERT INTO ` + "`" + `keytoken` + "`" + ` (id, account_id, refresh_token, refresh_tokens_used) 
VALUES (?, ?, ?, COALESCE(?, JSON_ARRAY()))
`

type InsertKeyParams struct {
	ID           string
	AccountID    string
	RefreshToken string
	Column4      interface{}
}

func (q *Queries) InsertKey(ctx context.Context, arg InsertKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertKey,
		arg.ID,
		arg.AccountID,
		arg.RefreshToken,
		arg.Column4,
	)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE ` + "`" + `keytoken` + "`" + ` 
SET refresh_token = ?, update_at = CURRENT_TIMESTAMP
WHERE account_id = ?
`

type UpdateRefreshTokenParams struct {
	RefreshToken string
	AccountID    string
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken, arg.RefreshToken, arg.AccountID)
	return err
}

const updateRefreshTokenAndUsedTokens = `-- name: UpdateRefreshTokenAndUsedTokens :exec
UPDATE ` + "`" + `keytoken` + "`" + `
SET refresh_token = ?, 
    refresh_tokens_used = CASE
        WHEN refresh_tokens_used IS NULL THEN JSON_ARRAY(?)
        ELSE JSON_ARRAY_APPEND(refresh_tokens_used, '$', ?)
    END,
    update_at = CURRENT_TIMESTAMP
WHERE account_id = ?
`

type UpdateRefreshTokenAndUsedTokensParams struct {
	RefreshToken    string
	JSONARRAY       interface{}
	JSONARRAYAPPEND interface{}
	AccountID       string
}

func (q *Queries) UpdateRefreshTokenAndUsedTokens(ctx context.Context, arg UpdateRefreshTokenAndUsedTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenAndUsedTokens,
		arg.RefreshToken,
		arg.JSONARRAY,
		arg.JSONARRAYAPPEND,
		arg.AccountID,
	)
	return err
}
