// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 0006_roleaccount.sql

package database

import (
	"context"
	"time"
)

const createRoleAccount = `-- name: CreateRoleAccount :exec
INSERT INTO ` + "`" + `role_account` + "`" + ` (id, account_id, role_id, license_id, is_deleted, create_at, update_at)
VALUES (?, ?, ?, ?, false, NOW(), NOW())
`

type CreateRoleAccountParams struct {
	ID        string
	AccountID string
	RoleID    string
	LicenseID string
}

func (q *Queries) CreateRoleAccount(ctx context.Context, arg CreateRoleAccountParams) error {
	_, err := q.db.ExecContext(ctx, createRoleAccount,
		arg.ID,
		arg.AccountID,
		arg.RoleID,
		arg.LicenseID,
	)
	return err
}

const deleteRoleAccount = `-- name: DeleteRoleAccount :exec
UPDATE ` + "`" + `role_account` + "`" + `
SET is_deleted = true, update_at = ?
WHERE id = ?
`

type DeleteRoleAccountParams struct {
	UpdateAt time.Time
	ID       string
}

func (q *Queries) DeleteRoleAccount(ctx context.Context, arg DeleteRoleAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteRoleAccount, arg.UpdateAt, arg.ID)
	return err
}

const getAllRoleAccount = `-- name: GetAllRoleAccount :many
SELECT id, account_id, role_id, license_id
FROM ` + "`" + `role_account` + "`" + `
WHERE is_deleted = false
`

type GetAllRoleAccountRow struct {
	ID        string
	AccountID string
	RoleID    string
	LicenseID string
}

func (q *Queries) GetAllRoleAccount(ctx context.Context) ([]GetAllRoleAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoleAccount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRoleAccountRow
	for rows.Next() {
		var i GetAllRoleAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RoleID,
			&i.LicenseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleAccountByAccountId = `-- name: GetRoleAccountByAccountId :many
SELECT id, account_id, role_id, license_id
FROM ` + "`" + `role_account` + "`" + `
WHERE is_deleted = false AND account_id = ?
`

type GetRoleAccountByAccountIdRow struct {
	ID        string
	AccountID string
	RoleID    string
	LicenseID string
}

func (q *Queries) GetRoleAccountByAccountId(ctx context.Context, accountID string) ([]GetRoleAccountByAccountIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoleAccountByAccountId, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoleAccountByAccountIdRow
	for rows.Next() {
		var i GetRoleAccountByAccountIdRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RoleID,
			&i.LicenseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleAccountById = `-- name: GetRoleAccountById :one
SELECT id, account_id, role_id, license_id
FROM ` + "`" + `role_account` + "`" + `
WHERE is_deleted = false AND id = ?
`

type GetRoleAccountByIdRow struct {
	ID        string
	AccountID string
	RoleID    string
	LicenseID string
}

func (q *Queries) GetRoleAccountById(ctx context.Context, id string) (GetRoleAccountByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getRoleAccountById, id)
	var i GetRoleAccountByIdRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RoleID,
		&i.LicenseID,
	)
	return i, err
}

const getRoleAccountByRoleId = `-- name: GetRoleAccountByRoleId :many
SELECT id, account_id, role_id, license_id,create_at,update_at
FROM ` + "`" + `role_account` + "`" + `
WHERE is_deleted = false AND role_id = ?
`

type GetRoleAccountByRoleIdRow struct {
	ID        string
	AccountID string
	RoleID    string
	LicenseID string
	CreateAt  time.Time
	UpdateAt  time.Time
}

func (q *Queries) GetRoleAccountByRoleId(ctx context.Context, roleID string) ([]GetRoleAccountByRoleIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoleAccountByRoleId, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoleAccountByRoleIdRow
	for rows.Next() {
		var i GetRoleAccountByRoleIdRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.RoleID,
			&i.LicenseID,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleAccount = `-- name: UpdateRoleAccount :exec
UPDATE ` + "`" + `role_account` + "`" + `
SET account_id = ?, role_id = ?, license_id = ?
WHERE id = ?
`

type UpdateRoleAccountParams struct {
	AccountID string
	RoleID    string
	LicenseID string
	ID        string
}

func (q *Queries) UpdateRoleAccount(ctx context.Context, arg UpdateRoleAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateRoleAccount,
		arg.AccountID,
		arg.RoleID,
		arg.LicenseID,
		arg.ID,
	)
	return err
}
