// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

// account
type Account struct {
	ID       string
	Name     string
	Email    string
	Password string
	Salt     string
	// [active,inactive]
	Status    bool
	Images    string
	IsDeleted bool
	CreateAt  time.Time
	UpdateAt  time.Time
}
