// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

// account
type Account struct {
	ID       string
	Number   int32
	Code     string
	Name     string
	Email    string
	Username string
	Password string
	Salt     string
	// [active,inactive]
	Status    bool
	Images    string
	CreatedBy string
	IsDeleted bool
	CreateAt  time.Time
	UpdateAt  time.Time
}

// keytoken
type Keytoken struct {
	ID                string
	AccountID         string
	RefreshToken      string
	RefreshTokensUsed json.RawMessage
	CreateAt          time.Time
	UpdateAt          time.Time
}

type License struct {
	ID        string
	License   string
	RoleID    string
	DateStart time.Time
	DateEnd   string
	CreatedAt time.Time
	UpdateAt  time.Time
	IsDeleted bool
}

type Menu struct {
	ID              string
	MenuName        string
	MenuIcon        string
	MenuUrl         string
	MenuParentID    sql.NullString
	MenuLevel       int32
	MenuNumberOrder int32
	MenuGroupName   string
	IsDeleted       bool
	CreateAt        time.Time
	UpdateAt        time.Time
}

type Role struct {
	ID             string
	Code           string
	RoleName       string
	RoleLeftValue  int32
	RoleRightValue int32
	RoleMaxNumber  int32
	LicenseID      string
	CreatedBy      string
	IsDeleted      bool
	CreateAt       time.Time
	UpdateAt       time.Time
}

type RoleAccount struct {
	ID        string
	AccountID string
	RoleID    string
	CreatedBy sql.NullString
	IsDeleted bool
	CreateAt  time.Time
	UpdateAt  time.Time
}

type RolesMenu struct {
	ID         string
	MenuID     string
	RoleID     string
	ListMethod json.RawMessage
	IsDeleted  bool
	CreateAt   time.Time
	UpdateAt   time.Time
}
