// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

// account
type Account struct {
	ID       string
	Number   int32
	Name     string
	Email    string
	Password string
	Salt     string
	// [active,inactive]
	Status    bool
	Images    string
	IsDeleted bool
	CreateAt  time.Time
	UpdateAt  time.Time
}

// keytoken
type Keytoken struct {
	ID                string
	AccountID         string
	RefreshToken      string
	RefreshTokensUsed json.RawMessage
	CreateAt          time.Time
	UpdateAt          time.Time
}

type Menu struct {
	ID              string
	MenuName        string
	MenuIcon        string
	MenuUrl         string
	MenuParentID    sql.NullString
	MenuLevel       int32
	MenuNumberOrder float64
	MenuGroupName   string
	IsDeleted       bool
	CreateAt        time.Time
	UpdateAt        time.Time
}
