basePath: /v1/2025
definitions:
  model.AccountInput:
    properties:
      email:
        type: string
      images:
        type: string
      name:
        type: string
      password:
        type: string
      status:
        type: boolean
    type: object
  model.ChangePasswordInput:
    properties:
      password:
        type: string
    type: object
  model.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.MenuInput:
    properties:
      id:
        type: string
      menu_group_name:
        type: string
      menu_icon:
        type: string
      menu_level:
        type: integer
      menu_name:
        type: string
      menu_number_order:
        type: integer
      menu_parent_id:
        type: string
      menu_url:
        type: string
    type: object
  model.Role:
    properties:
      code:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: string
      is_deleted:
        type: boolean
      is_licensed:
        type: boolean
      role_left_value:
        type: integer
      role_max_number:
        type: integer
      role_name:
        type: string
      role_right_value:
        type: integer
      updated_by:
        type: string
    type: object
  model.RolesMenu:
    properties:
      list_method:
        example:
        - '[''GET'''
        - '''POST'']'
        items:
          type: string
        type: array
      menu_id:
        example: menu-123
        type: string
      role_id:
        example: role-123
        type: string
    type: object
  response.ErrorResponseData:
    properties:
      code:
        description: status code
        type: integer
      detail:
        description: dữ liệu được return
      error:
        description: Thông báo lỗi
        type: string
    type: object
  response.ResponseData:
    properties:
      code:
        description: status code
        type: integer
      data:
        description: dữ liệu được return
      message:
        description: Thông báo lỗi
        type: string
    type: object
host: localhost:8002
info:
  contact:
    email: teamaithacoindustries@gmail.com
    name: TEAM AI
    url: github.com/phananhtu1998/go-backend-api
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: github.com/phananhtu1998/go-backend-api
  title: API DOCUMENTATION PARKING BACKEND
  version: 1.0.0
paths:
  /admin/create_account:
    post:
      consumes:
      - application/json
      description: API này cho phép tạo tài khoản mới
      parameters:
      - description: Thông tin tài khoản cần tạo
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Tạo tài khoản mới
      tags:
      - Account management
  /admin/delete_account/{id}:
    delete:
      consumes:
      - application/json
      description: API này xóa tài khoản dựa trên ID
      parameters:
      - description: ID của tài khoản cần xóa
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Xóa tài khoản
      tags:
      - Account management
  /admin/get_account_by_id/{id}:
    get:
      consumes:
      - application/json
      description: API này trả về tài khoản theo ID
      parameters:
      - description: ID tài khoản cần lấy
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Lấy tài khoản theo ID
      tags:
      - Account management
  /admin/get_all_account:
    get:
      consumes:
      - application/json
      description: API này trả về danh sách tất cả tài khoản trong hệ thống
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Lấy danh sách tất cả tài khoản
      tags:
      - Account management
  /admin/update_account/{id}:
    put:
      consumes:
      - application/json
      description: API này cập nhật thông tin tài khoản dựa trên ID
      parameters:
      - description: ID tài khoản cần cập nhật
        in: path
        name: id
        required: true
        type: string
      - description: Dữ liệu cập nhật tài khoản
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Cập nhật tài khoản
      tags:
      - Account management
  /auth/change_password:
    post:
      consumes:
      - application/json
      description: ChangePassword
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.ChangePasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: ChangePassword
      tags:
      - Authenticate
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: Login
      tags:
      - Authenticate
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Logout
      tags:
      - Authenticate
  /auth/refreshtoken:
    post:
      consumes:
      - application/json
      description: RefreshToken
      parameters:
      - description: Refresh Token
        in: header
        name: RefreshToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: RefreshToken
      tags:
      - Authenticate
  /menu/create_menu:
    post:
      consumes:
      - application/json
      description: API tạo menu trong hệ thống
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.MenuInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Tạo menu
      tags:
      - Menu
  /menu/delete/{id}:
    delete:
      consumes:
      - application/json
      description: API này xóa một menu dựa trên ID
      parameters:
      - description: Menu ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Xóa menu
      tags:
      - Menu
  /menu/get_all_menu:
    get:
      consumes:
      - application/json
      description: API này trả về danh sách tất cả menu trong hệ thống
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Lấy danh sách tất cả menu
      tags:
      - Menu
  /menu/get_menu_by_id/{id}:
    get:
      consumes:
      - application/json
      description: API này trả về menu theo ID
      parameters:
      - description: ID menu cần lấy
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Lấy menu theo ID
      tags:
      - Menu
  /menu/update_multiple_menu:
    put:
      consumes:
      - application/json
      description: API này cập nhật danh sách menu dựa trên danh sách ID
      parameters:
      - description: Danh sách menu cần cập nhật
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/model.MenuInput'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Cập nhật nhiều menu
      tags:
      - Menu
  /role/create_role:
    post:
      consumes:
      - application/json
      description: Api tạo role trong hệ thống
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Tạo role
      tags:
      - Role
  /role/delete_role/{id}:
    delete:
      consumes:
      - application/json
      description: API xóa mềm role trong hệ thống
      parameters:
      - description: ID của role cần xóa
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Xóa role
      tags:
      - Role
  /role/get_all_roles:
    get:
      consumes:
      - application/json
      description: Api lấy danh sách role trong hệ thống
      parameters:
      - description: 'Số trang (mặc định: 1)'
        in: query
        name: page
        type: integer
      - description: 'Số lượng mỗi trang (mặc định: 20)'
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Lấy danh sách role
      tags:
      - Role
  /role/get_role_by_id/{id}:
    get:
      consumes:
      - application/json
      description: API này trả về role theo ID
      parameters:
      - description: ID role cần lấy
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Lấy role theo ID
      tags:
      - Role
  /rolesmenu/create_roles_menu:
    post:
      consumes:
      - application/json
      description: Create a new mapping between roles and menus in the system
      parameters:
      - description: Role menu mapping details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.RolesMenu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Create a new role menu mapping
      tags:
      - RolesMenu
  /rolesmenu/get_role_menu_by_role_id/{id}:
    get:
      consumes:
      - application/json
      description: API này trả về role menu theo ID
      parameters:
      - description: ID role
        in: path
        name: id
        required: true
        type: string
      - description: Từ khóa tìm kiếm
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      security:
      - BearerAuth: []
      summary: Lấy role menu theo ID
      tags:
      - RolesMenu
security:
- "":
  - BearerAuth
  - ApiKeyAuth
securityDefinitions:
  ApiKeyAuth:
    description: Nhập API Key vào header để xác thực API
    in: header
    name: X-API-Key
    type: apiKey
  BearerAuth:
    description: 'Nhập Bearer Token vào header. Ví dụ: "Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
