basePath: /v1/2025
definitions:
  response.ErrorResponseData:
    properties:
      code:
        description: status code
        type: integer
      detail:
        description: dữ liệu được return
      error:
        description: Thông báo lỗi
        type: string
    type: object
  response.ResponseData:
    properties:
      code:
        description: status code
        type: integer
      data:
        description: dữ liệu được return
      message:
        description: Thông báo lỗi
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8002
info:
  contact:
    email: teamaithacoindustries@gmail.com
    name: TEAM AI
    url: github.com/phananhtu1998/go-backend-api
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: github.com/phananhtu1998/go-backend-api
  title: API DOCUMENTATION PARKING BACKEND
  version: 1.0.0
paths:
  /admin/get_account_by_id/{id}:
    get:
      consumes:
      - application/json
      description: API này trả về tài khoản theo ID
      parameters:
      - description: ID tài khoản cần lấy
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: Lấy tài khoản theo ID
      tags:
      - account management
  /admin/get_all_account:
    get:
      consumes:
      - application/json
      description: API này trả về danh sách tất cả tài khoản trong hệ thống
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: Lấy danh sách tất cả tài khoản
      tags:
      - account management
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
