package main

import (
	_ "go-backend-api/cmd/swag/docs"
	"go-backend-api/internal/initialize"

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
	// docs is generated by Swag CLI, you have to import it.
)

// @title           API DOCUMENTATION PARKING BACKEND
// @version         1.0.0
// @description     This is a sample server celler server.
// @termsOfService  github.com/phananhtu1998/go-backend-api

// @contact.name   TEAM AI
// @contact.url    github.com/phananhtu1998/go-backend-api
// @contact.email  teamaithacoindustries@gmail.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8002
// @BasePath  /v1/2025
// @schema http
// @securityDefinitions.basic  BasicAuth

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/

func main() {
	r := initialize.Run()
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run(":8002")
}
